# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/40__main__.ipynb.

# %% ../nbs/40__main__.ipynb 4
from __future__ import annotations

import sys
from .mcp import main

# %% auto 0
__all__ = []

# %% ../nbs/40__main__.ipynb 6
#| eval: False
if __name__ == "__main__":
    sys.exit(main())

# %% ../nbs/40__main__.ipynb 8
#| export

