"""**DEPRECATED**: This module is deprecated. Use `nbdev_mcp.install` instead."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/40_installer.ipynb.

# %% ../nbs/40_installer.ipynb 4
from __future__ import annotations
import warnings

# Re-export everything from new install module for backward compatibility
from nbdev_mcp.install import (
    # Types
    InstallResult, MCPServerConfig,
    # Installers
    ClaudeInstaller, CodexInstaller, VSCodeInstaller, OllamaInstaller,
    # Convenience functions
    install_claude, install_codex, install_vscode, install_ollama,
    uninstall_claude, uninstall_codex, uninstall_vscode, uninstall_ollama,
    install_all, uninstall_all, check_status,
    # Path functions (with aliases for backward compatibility)
    get_claude_config_path, get_codex_config_path,
    get_vscode_mcp_path as get_vscode_config_path,
    get_ollama_config_path,
    # Utilities
    get_python_path
)

# %% auto 0
__all__ = ['get_vscode_config', 'get_claude_config', 'get_codex_config', 'open_config', 'main']

# %% ../nbs/40_installer.ipynb 6
def get_vscode_config(python_path: str) -> dict:
    """DEPRECATED: Use MCPServerConfig.for_nbdev().to_vscode_format() instead."""
    warnings.warn(
        "get_vscode_config is deprecated. Use MCPServerConfig.for_nbdev().to_vscode_format()",
        DeprecationWarning,
        stacklevel=2
    )
    return MCPServerConfig.for_nbdev(python_path).to_vscode_format()

# %% ../nbs/40_installer.ipynb 7
def get_claude_config(python_path: str) -> dict:
    """DEPRECATED: Use MCPServerConfig.for_nbdev().to_claude_format() instead."""
    warnings.warn(
        "get_claude_config is deprecated. Use MCPServerConfig.for_nbdev().to_claude_format()",
        DeprecationWarning,
        stacklevel=2
    )
    return MCPServerConfig.for_nbdev(python_path).to_claude_format()

# %% ../nbs/40_installer.ipynb 8
def get_codex_config(python_path: str) -> str:
    """DEPRECATED: Use MCPServerConfig.for_nbdev().to_toml_section() instead."""
    warnings.warn(
        "get_codex_config is deprecated. Use MCPServerConfig.for_nbdev().to_toml_section()",
        DeprecationWarning,
        stacklevel=2
    )
    return MCPServerConfig.for_nbdev(python_path).to_toml_section()

# %% ../nbs/40_installer.ipynb 9
def open_config(tool: str) -> bool:
    """DEPRECATED: Use nbdev_mcp.utils.io.open_file_in_editor() instead."""
    warnings.warn(
        "open_config is deprecated. Use nbdev_mcp.utils.io.open_file_in_editor()",
        DeprecationWarning,
        stacklevel=2
    )
    from nbdev_mcp.utils.io import open_file_in_editor
    paths = {
        'vscode': get_vscode_config_path,
        'claude': get_claude_config_path,
        'codex': get_codex_config_path,
        'ollama': get_ollama_config_path,
    }
    if tool not in paths:
        return False
    return open_file_in_editor(paths[tool]())

# %% ../nbs/40_installer.ipynb 11
def main():
    """DEPRECATED CLI entry point. Use nbdev_mcp.install CLI instead."""
    import argparse
    
    warnings.warn(
        "nbdev-mcp-install CLI is deprecated. Functionality is now in nbdev_mcp.install",
        DeprecationWarning,
        stacklevel=2
    )
    
    parser = argparse.ArgumentParser(
        prog="nbdev-mcp-install",
        description="DEPRECATED: Install nbdev-mcp configuration for AI tools."
    )
    
    subparsers = parser.add_subparsers(dest="command", help="Commands")
    
    # Status command
    subparsers.add_parser("status", help="Check installation status")
    
    # Install command
    install_parser = subparsers.add_parser("install", help="Install configuration")
    install_parser.add_argument(
        "tool", nargs="?",
        choices=["vscode", "claude", "codex", "ollama", "all"],
        default="all", help="Tool to configure (default: all)"
    )
    install_parser.add_argument("--python", "-p", help="Python interpreter path")
    install_parser.add_argument("--force", "-f", action="store_true", help="Overwrite existing")
    install_parser.add_argument("--dry-run", "-n", action="store_true", help="Show what would be done")
    
    args = parser.parse_args()
    
    if args.command == "status" or args.command is None:
        statuses = check_status()
        print(f"\nPython: {get_python_path()}\n")
        print("Installation Status:")
        print("-" * 60)
        for status in statuses:
            icon = "✓" if status['configured'] else "✗"
            exists = "exists" if status['exists'] else "missing"
            print(f"  {icon} {status['provider']:8} - {exists:8} - {status['path']}")
        print()
        
    elif args.command == "install":
        providers = None if args.tool == "all" else [args.tool]
        results = install_all(
            python_path=args.python,
            force=args.force,
            dry_run=args.dry_run,
            providers=providers
        )
        for result in results:
            icon = "✓" if result.success else "✗"
            print(f"{icon} {result.message}")
