"""Configuration paths for each provider and location"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/50_install/02_paths.ipynb.

# %% ../../nbs/50_install/02_paths.ipynb 4
from __future__ import annotations
import os
from pathlib import Path
from typing import Optional

from .base import get_platform

# %% auto 0
__all__ = ['get_vscode_user_dir', 'get_vscode_mcp_path', 'get_vscode_settings_path', 'get_claude_config_dir',
           'get_claude_config_path', 'get_claude_mcp_path', 'get_codex_config_dir', 'get_codex_config_path',
           'get_ollama_config_dir', 'get_ollama_config_path', 'get_project_mcp_path', 'get_project_claude_path',
           'get_all_config_paths', 'get_config_path']

# %% ../../nbs/50_install/02_paths.ipynb 6
def get_vscode_user_dir() -> Path:
    """Get VS Code user settings directory."""
    plat = get_platform()
    if plat == 'darwin':
        return Path.home() / 'Library' / 'Application Support' / 'Code' / 'User'
    elif plat == 'windows':
        return Path(os.environ.get('APPDATA', '')) / 'Code' / 'User'
    else:
        return Path.home() / '.config' / 'Code' / 'User'


def get_vscode_mcp_path() -> Path:
    """Get VS Code MCP configuration path."""
    return get_vscode_user_dir() / 'mcp.json'


def get_vscode_settings_path() -> Path:
    """Get VS Code settings.json path."""
    return get_vscode_user_dir() / 'settings.json'

# %% ../../nbs/50_install/02_paths.ipynb 8
def get_claude_config_dir() -> Path:
    """Get Claude Code configuration directory."""
    return Path.home() / '.claude'


def get_claude_config_path() -> Path:
    """Get Claude Code main config path (~/.claude.json)."""
    return Path.home() / '.claude.json'


def get_claude_mcp_path() -> Path:
    """Get Claude Code MCP servers config path.
    
    This is inside the .claude directory.
    """
    return get_claude_config_dir() / 'mcp_servers.json'

# %% ../../nbs/50_install/02_paths.ipynb 10
def get_codex_config_dir() -> Path:
    """Get Codex configuration directory."""
    return Path.home() / '.codex'


def get_codex_config_path() -> Path:
    """Get Codex config.toml path."""
    return get_codex_config_dir() / 'config.toml'

# %% ../../nbs/50_install/02_paths.ipynb 12
def get_ollama_config_dir() -> Path:
    """Get Ollama configuration directory."""
    plat = get_platform()
    if plat == 'darwin':
        return Path.home() / '.ollama'
    elif plat == 'windows':
        return Path(os.environ.get('LOCALAPPDATA', '')) / 'Ollama'
    else:
        return Path.home() / '.ollama'


def get_ollama_config_path() -> Path:
    """Get Ollama configuration path."""
    return get_ollama_config_dir() / 'config.json'

# %% ../../nbs/50_install/02_paths.ipynb 14
def get_project_mcp_path(project_dir: Optional[Path] = None) -> Path:
    """Get project-level MCP config path.
    
    This is for project-specific MCP configurations.
    """
    project = project_dir or Path.cwd()
    return project / '.mcp.json'


def get_project_claude_path(project_dir: Optional[Path] = None) -> Path:
    """Get project-level Claude config path."""
    project = project_dir or Path.cwd()
    return project / '.claude' / 'mcp.json'

# %% ../../nbs/50_install/02_paths.ipynb 16
def get_all_config_paths() -> dict[str, Path]:
    """Get all known configuration paths.
    
    Returns
    -------
    dict[str, Path]
        Mapping of provider name to config path.
    """
    return {
        'vscode': get_vscode_mcp_path(),
        'claude': get_claude_config_path(),
        'codex': get_codex_config_path(),
        'ollama': get_ollama_config_path(),
    }


def get_config_path(provider: str) -> Optional[Path]:
    """Get config path for a specific provider.
    
    Parameters
    ----------
    provider : str
        Provider name (vscode, claude, codex, ollama).
    
    Returns
    -------
    Optional[Path]
        Config path or None if unknown provider.
    """
    paths = get_all_config_paths()
    return paths.get(provider.lower())
