"""Core regular expression patterns"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/00_utils/05_re.ipynb.

# %% ../../nbs/00_utils/05_re.ipynb #8d71e546
from __future__ import annotations
from typing import Dict, Optional, Any
import os, re, json
from pathlib import Path
from types import SimpleNamespace

# %% auto #0
__all__ = ['HEADER_PATTERN', 'REFERENCE_PATTERN', 'REF_LINK_USAGE_PATTERN', 'BARE_REF_PATTERN', 'TODO_CODE_PATTERN',
           'TODO_MD_PATTERN', 'BUG_CODE_PATTERN', 'BUG_MD_PATTERN', 'BUG_PATTERN', 'RELATIVE_IMPORT_PATTERN',
           'RELATIVE_LEVEL_PATTERN', 'IMPORT_FROM_PATTERN', 'IMPORT_PATTERN', 'EXPORT_DIRECTIVE_PATTERN',
           'EXPORTA_DIRECTIVE_PATTERN', 'EXPORT_ANY_RE', 'DEFAULT_EXP_PATTERN', 'HIDE_DIRECTIVE_PATTERN',
           'EVAL_FALSE_PATTERN', 'FUNCTION_DEF_PATTERN', 'ASYNC_FUNCTION_DEF_PATTERN', 'CLASS_DEF_PATTERN',
           'ALL_DEFINITION_PATTERN', 'TEST_FUNCTION_PATTERN', 'ASSERT_PATTERN', 'PYTEST_MARKER_PATTERN',
           'MAIN_GUARD_PATTERN', 'EXPORT_MAIN_PATTERN', 'YAML_NAME_PATTERN', 'NBDEV_CELL_COMMENT_PATTERN',
           'DIGIT_PREFIX', 'NBDEV_FILE_PREFIX', 'NUMBERED_NOTEBOOK_PATTERN', 'PATTERN_CATALOG']

# %% ../../nbs/00_utils/05_re.ipynb #ebc402d4
HEADER_PATTERN = re.compile(r"^#{1,6}\s")
'''Match markdown headers (e.g., `# H1`, `## H2`).'''

REFERENCE_PATTERN = re.compile(r"^\s*\[([^\]]+)\]:\s*(.+)$")
'''Reference-style markdown links: `[id]: https://example.com`.'''

REF_LINK_USAGE_PATTERN = re.compile(r"\[([^\]]+)\]\[([^\]]+)\]")
'''Match markdown reference link usage: `[text][id]`.'''

BARE_REF_PATTERN = re.compile(r"(?<!\!)\[(?!\[)([^\]]+)\](?!\()")
'''Match bare reference link: `[id]` (not images, not followed by parens).'''

# %% ../../nbs/00_utils/05_re.ipynb #212cbde5
TODO_CODE_PATTERN = re.compile(r"#\s*TODO:?\s*(.*)", re.IGNORECASE)
'''TODO comments inside code cells: `# TODO: fix this`.'''

TODO_MD_PATTERN = re.compile(r"(?:^|\s)TODO:?(.+)", re.IGNORECASE)
'''TODO call-outs inside markdown content.'''

BUG_CODE_PATTERN = re.compile(r"#\s*BUG:?\s*(.*)", re.IGNORECASE)
'''BUG comments inside code cells: `# BUG: known issue`.'''

BUG_MD_PATTERN = re.compile(r"(?:^|\s)BUG:?\s*(.*)", re.IGNORECASE)
'''BUG markers inside markdown cells.'''

BUG_PATTERN = re.compile(r"(?:#\s*)?BUG:?\s*(.*)", re.IGNORECASE)
'''General BUG pattern matching both code (`# BUG:`) and markdown (`BUG:`) formats.'''


# %% ../../nbs/00_utils/05_re.ipynb #c499b061
RELATIVE_IMPORT_PATTERN = re.compile(r"^\s*from\s+(\.+[\w\.]*)\s+import\s+(.+)$")
'''Detect relative imports so tooling can flag / rewrite them.'''

RELATIVE_LEVEL_PATTERN = re.compile(r"^(\.+)(.*)$")
'''Parse relative import levels (e.g., `..foo` -> level=2, module=foo).'''
# RELATIVE_IMPORT_PATTERN = re.compile(r"(\.+)(.*)$")

IMPORT_FROM_PATTERN = re.compile(r"^\s*from\s+([\w\.]+)\s+import\s+", re.MULTILINE)
'''Match `from module import ...` statements.'''

IMPORT_PATTERN = re.compile(r"^\s*import\s+([\w\.]+)", re.MULTILINE)
'''Match `import module` statements.'''

# %% ../../nbs/00_utils/05_re.ipynb #fb7b2b2f
EXPORT_DIRECTIVE_PATTERN = re.compile(r"^\s*#\|\s*exporti?\b", re.MULTILINE)
'''Match nbdev export directives (`#| export`, `#| exporti`) in code cells.'''

EXPORTA_DIRECTIVE_PATTERN = re.compile(r"^\s*#\|\s*exporta\b", re.MULTILINE)
'''Match nbdev exporta directive (`#| exporta` = export all) in code cells.'''

EXPORT_ANY_RE = re.compile(r'^\s*#\|\s*export[ia]?\b', re.MULTILINE)
'''Combined pattern for any export directive (export, exporti, exporta).'''

DEFAULT_EXP_PATTERN = re.compile(r"#\|\s*default_exp\s+([\w\.]+)")
'''Capture nbdev default_exp module targets from notebooks.'''

HIDE_DIRECTIVE_PATTERN = re.compile(r"^\s*#\|\s*hide\b", re.MULTILINE)
'''Match nbdev hide directive (`#| hide`) in code cells.'''

EVAL_FALSE_PATTERN = re.compile(r"^\s*#\|\s*eval:\s*false\b", re.MULTILINE | re.IGNORECASE)
'''Match nbdev eval:false directive to skip cell execution during tests.'''


# %% ../../nbs/00_utils/05_re.ipynb #8cf82ff5
FUNCTION_DEF_PATTERN = re.compile(r"^\s*def\s+(\w+)\s*\(", re.MULTILINE)
'''Match function definitions and capture the function name.'''

ASYNC_FUNCTION_DEF_PATTERN = re.compile(r"^\s*async\s+def\s+(\w+)\s*\(", re.MULTILINE)
'''Match async function definitions and capture the function name.'''

CLASS_DEF_PATTERN = re.compile(r"^\s*class\s+(\w+)\s*[\(:]", re.MULTILINE)
'''Match class definitions and capture the class name.'''

ALL_DEFINITION_PATTERN = re.compile(r"^\s*__all__\s*=", re.MULTILINE)
'''Detect `__all__` definitions in modules.'''

# %% ../../nbs/00_utils/05_re.ipynb #f82a44be
TEST_FUNCTION_PATTERN = re.compile(r"^\s*def\s+test_\w+\s*\(", re.MULTILINE)
'''Match test function definitions (def test_*).'''

ASSERT_PATTERN = re.compile(r"^\s*assert\s+", re.MULTILINE)
'''Match assert statements in code.'''

PYTEST_MARKER_PATTERN = re.compile(r"@pytest\.mark\.\w+", re.MULTILINE)
'''Match pytest markers (@pytest.mark.*).'''

# %% ../../nbs/00_utils/05_re.ipynb #8ef5f4ec
MAIN_GUARD_PATTERN = re.compile(r"^\s*if\s+__name__\s*==\s*['\"]__main__['\"]\s*:", re.MULTILINE)
'''Detect `if __name__ == "__main__":` guards in code cells.'''

EXPORT_MAIN_PATTERN = re.compile(r"^\s*#\|\s*export\s+__main__", re.MULTILINE | re.IGNORECASE)
'''Match `#| export __main__` directive for safe main module exports.'''

# %% ../../nbs/00_utils/05_re.ipynb #1710b3ec
YAML_NAME_PATTERN = re.compile(r"^\s*name\s*:\s*([A-Za-z0-9._-]+)\s*$")
'''Extract environment name from conda/mamba YAML files.'''

NBDEV_CELL_COMMENT_PATTERN = re.compile(r"#\s*%%\s*(\.\./nbs/[\w/]+\.ipynb)\s+(\d+)")
'''Match nbdev cell comments in generated .py files: `# %% ../nbs/04_nb.ipynb 5`.'''

DIGIT_PREFIX = re.compile(r"^\d+_")
'''Match digit prefix e.g. `04_nb.ipynb`.'''

NBDEV_FILE_PREFIX = re.compile(r'^\\d+[a-z]?_')
'''Match nbdev file prefix e.g. `04_nb.ipynb` or `04a_special.ipynb`.'''

NUMBERED_NOTEBOOK_PATTERN = re.compile(r"^\d{2}_.+\.ipynb$")
'''Match properly numbered nbdev notebooks (e.g., `00_core.ipynb`, `01_utils.ipynb`).'''

# %% ../../nbs/00_utils/05_re.ipynb #54266483
PATTERN_CATALOG: Dict[str, re.Pattern] = {
    # Markdown
    "header": HEADER_PATTERN,
    "reference_link": REFERENCE_PATTERN,
    "ref_link_usage": REF_LINK_USAGE_PATTERN,
    "bare_ref": BARE_REF_PATTERN,
    # Comments
    "todo_code": TODO_CODE_PATTERN,
    "todo_markdown": TODO_MD_PATTERN,
    "bug_code": BUG_CODE_PATTERN,
    "bug_markdown": BUG_MD_PATTERN,
    "bug": BUG_PATTERN,
    # Imports
    "relative_import": RELATIVE_IMPORT_PATTERN,
    "relative_level": RELATIVE_LEVEL_PATTERN,
    "import_from": IMPORT_FROM_PATTERN,
    "import": IMPORT_PATTERN,
    # nbdev directives
    "export_directive": EXPORT_DIRECTIVE_PATTERN,
    "exporta_directive": EXPORTA_DIRECTIVE_PATTERN,
    "export_any": EXPORT_ANY_RE,
    "default_exp": DEFAULT_EXP_PATTERN,
    "hide_directive": HIDE_DIRECTIVE_PATTERN,
    "eval_false": EVAL_FALSE_PATTERN,
    "export_main": EXPORT_MAIN_PATTERN,
    # Symbol definitions
    "function_def": FUNCTION_DEF_PATTERN,
    "async_function_def": ASYNC_FUNCTION_DEF_PATTERN,
    "class_def": CLASS_DEF_PATTERN,
    "all_definition": ALL_DEFINITION_PATTERN,
    # Tests
    "test_function": TEST_FUNCTION_PATTERN,
    "assert": ASSERT_PATTERN,
    "pytest_marker": PYTEST_MARKER_PATTERN,
    # Code
    "main_guard": MAIN_GUARD_PATTERN,
    # File mapping
    "yaml_name": YAML_NAME_PATTERN,
    "nbdev_cell_comment": NBDEV_CELL_COMMENT_PATTERN,
    "digit_prefix": DIGIT_PREFIX,
    "nbdev_file_prefix": NBDEV_FILE_PREFIX,
    "numbered_notebook": NUMBERED_NOTEBOOK_PATTERN,
}
'''Lookup of named regular expressions used across the MCP codebase.'''

# %% ../../nbs/00_utils/05_re.ipynb #beb36890
#| export
