"""End-to-end testing framework for agent MCP usage patterns"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/99_tests/01_agent_e2e.ipynb.

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #f12fa806
from __future__ import annotations
from typing import Any, Dict, List, Optional, Callable
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
import json
import hashlib
import time

from mcp.server.fastmcp import Context

# %% auto #0
__all__ = ['EDIT_PY_FILE_SCENARIO', 'FIX_LINT_SCENARIO', 'EXPLORE_CODEBASE_SCENARIO', 'FIND_DUPLICATES_SCENARIO',
           'RUN_TESTS_SCENARIO', 'SCENARIOS', 'TEST_PROMPTS', 'ToolCall', 'ToolCallSession', 'TestScenario',
           'McpRecorder', 'run_scenario_validation', 'analyze_session_efficiency', 'get_recorder', 'start_recording',
           'stop_recording', 'is_recording', 'record_call', 'enable_auto_recording', 'create_test_project',
           'cleanup_test_project', 'get_test_prompt', 'run_agent_test', 'run_all_agent_tests', 'add_recording_tools']

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #54ecc06b
@dataclass
class ToolCall:
    """Record of a single MCP tool call."""
    tool_name: str
    args: Dict[str, Any]
    result: Optional[Dict[str, Any]] = None
    timestamp: float = field(default_factory=time.time)
    duration_ms: float = 0.0
    success: bool = True
    error: Optional[str] = None
    
    @property
    def args_hash(self) -> str:
        """Hash of args for deduplication detection."""
        return hashlib.md5(json.dumps(self.args, sort_keys=True).encode()).hexdigest()[:8]
    
    def __repr__(self):
        status = "✓" if self.success else "✗"
        return f"{status} {self.tool_name}({self.args_hash}) [{self.duration_ms:.0f}ms]"

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #63338ee3
@dataclass
class ToolCallSession:
    """Collection of tool calls in a session with analysis capabilities."""
    calls: List[ToolCall] = field(default_factory=list)
    session_id: str = field(default_factory=lambda: datetime.now().strftime("%Y%m%d_%H%M%S"))
    
    def add(self, call: ToolCall) -> None:
        """Add a tool call to the session."""
        self.calls.append(call)
    
    def find_duplicates(self) -> List[tuple[ToolCall, ToolCall]]:
        """Find duplicate tool calls (same tool + args)."""
        seen: Dict[str, ToolCall] = {}
        duplicates = []
        for call in self.calls:
            key = f"{call.tool_name}:{call.args_hash}"
            if key in seen:
                duplicates.append((seen[key], call))
            else:
                seen[key] = call
        return duplicates
    
    def get_tool_counts(self) -> Dict[str, int]:
        """Count calls per tool."""
        counts: Dict[str, int] = {}
        for call in self.calls:
            counts[call.tool_name] = counts.get(call.tool_name, 0) + 1
        return counts
    
    def get_sequence(self) -> List[str]:
        """Get sequence of tool names in order."""
        return [call.tool_name for call in self.calls]
    
    def contains_pattern(self, pattern: List[str]) -> bool:
        """Check if the session contains a specific sequence pattern."""
        seq = self.get_sequence()
        for i in range(len(seq) - len(pattern) + 1):
            if seq[i:i+len(pattern)] == pattern:
                return True
        return False
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize session to dict."""
        return {
            "session_id": self.session_id,
            "calls": [
                {
                    "tool_name": c.tool_name,
                    "args": c.args,
                    "timestamp": c.timestamp,
                    "duration_ms": c.duration_ms,
                    "success": c.success,
                    "error": c.error
                }
                for c in self.calls
            ],
            "stats": {
                "total_calls": len(self.calls),
                "unique_tools": len(set(c.tool_name for c in self.calls)),
                "duplicates": len(self.find_duplicates()),
                "success_rate": sum(1 for c in self.calls if c.success) / max(len(self.calls), 1)
            }
        }
    
    def save(self, path: Path) -> None:
        """Save session to JSON file."""
        path.write_text(json.dumps(self.to_dict(), indent=2))
    
    @classmethod
    def load(cls, path: Path) -> 'ToolCallSession':
        """Load session from JSON file."""
        data = json.loads(path.read_text())
        session = cls(session_id=data["session_id"])
        for c in data["calls"]:
            session.add(ToolCall(
                tool_name=c["tool_name"],
                args=c["args"],
                timestamp=c["timestamp"],
                duration_ms=c["duration_ms"],
                success=c["success"],
                error=c.get("error")
            ))
        return session

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #c608e0b5
@dataclass
class TestScenario:
    """Define expected agent behavior for a task."""
    name: str
    description: str
    prompt: str  # The task prompt to give the agent
    
    # Expected behaviors
    required_tools: List[str] = field(default_factory=list)  # Must call these
    forbidden_tools: List[str] = field(default_factory=list)  # Must NOT call
    required_patterns: List[List[str]] = field(default_factory=list)  # Must contain sequences
    max_duplicates: int = 0  # Maximum allowed duplicate calls
    
    def validate(self, session: ToolCallSession) -> Dict[str, Any]:
        """Validate a session against this scenario."""
        results = {
            "scenario": self.name,
            "passed": True,
            "failures": []
        }
        
        called_tools = set(c.tool_name for c in session.calls)
        
        # Check required tools
        for tool in self.required_tools:
            if tool not in called_tools:
                results["passed"] = False
                results["failures"].append(f"Missing required tool: {tool}")
        
        # Check forbidden tools
        for tool in self.forbidden_tools:
            if tool in called_tools:
                results["passed"] = False
                results["failures"].append(f"Used forbidden tool: {tool}")
        
        # Check patterns
        for pattern in self.required_patterns:
            if not session.contains_pattern(pattern):
                results["passed"] = False
                results["failures"].append(f"Missing pattern: {' -> '.join(pattern)}")
        
        # Check duplicates
        duplicates = session.find_duplicates()
        if len(duplicates) > self.max_duplicates:
            results["passed"] = False
            results["failures"].append(
                f"Too many duplicates: {len(duplicates)} (max {self.max_duplicates})"
            )
        
        results["stats"] = {
            "total_calls": len(session.calls),
            "unique_tools": len(called_tools),
            "duplicates": len(duplicates)
        }
        
        return results

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #14308ff1
EDIT_PY_FILE_SCENARIO = TestScenario(
    name="edit_py_file",
    description="Agent should check if file is generated before editing",
    prompt="Edit the function `foo` in nbdev_mcp/utils/paths.py to add logging",
    required_tools=["check_if_generated"],
    required_patterns=[["check_if_generated"]],  # Must check first
    max_duplicates=0
)

FIX_LINT_SCENARIO = TestScenario(
    name="fix_lint_errors",
    description="Agent should lint, fix, then verify",
    prompt="Fix all lint errors in this nbdev project",
    required_tools=["lint_rules"],
    max_duplicates=1  # One re-check allowed
)

EXPLORE_CODEBASE_SCENARIO = TestScenario(
    name="explore_codebase",
    description="Agent should use analysis tools efficiently",
    prompt="What modules does this project export?",
    required_tools=["current_project"],  # Should establish context
    forbidden_tools=["edit_notebook_cell"],  # Should not edit during exploration
    max_duplicates=0
)

FIND_DUPLICATES_SCENARIO = TestScenario(
    name="find_duplicates",
    description="Agent should use deduplication tools",
    prompt="Find and consolidate duplicate code in this project",
    required_tools=["find_duplicates"],
    max_duplicates=0
)

RUN_TESTS_SCENARIO = TestScenario(
    name="run_tests",
    description="Agent should run tests appropriately",
    prompt="Run the tests for this project and fix any failures",
    required_tools=["nbdev_test"],  # or pytest_run
    max_duplicates=1
)

SCENARIOS = {
    "edit_py_file": EDIT_PY_FILE_SCENARIO,
    "fix_lint": FIX_LINT_SCENARIO,
    "explore": EXPLORE_CODEBASE_SCENARIO,
    "find_duplicates": FIND_DUPLICATES_SCENARIO,
    "run_tests": RUN_TESTS_SCENARIO,
}

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #c8ca1ad1
class McpRecorder:
    """Middleware to record MCP tool calls."""
    
    def __init__(self, session: Optional[ToolCallSession] = None):
        self.session = session or ToolCallSession()
        self._original_handlers: Dict[str, Callable] = {}
    
    def wrap_tool(self, tool_name: str, handler: Callable) -> Callable:
        """Wrap a tool handler to record calls."""
        self._original_handlers[tool_name] = handler
        
        async def recorded_handler(**kwargs):
            start = time.time()
            call = ToolCall(tool_name=tool_name, args=kwargs)
            
            try:
                result = await handler(**kwargs)
                call.result = result
                call.success = result.get("ok", True) if isinstance(result, dict) else True
            except Exception as e:
                call.success = False
                call.error = str(e)
                raise
            finally:
                call.duration_ms = (time.time() - start) * 1000
                self.session.add(call)
            
            return result
        
        return recorded_handler
    
    def get_report(self) -> str:
        """Generate a human-readable report."""
        lines = [f"Session: {self.session.session_id}"]
        lines.append(f"Total calls: {len(self.session.calls)}")
        lines.append("")
        
        lines.append("Tool counts:")
        for tool, count in sorted(self.session.get_tool_counts().items()):
            lines.append(f"  {tool}: {count}")
        
        duplicates = self.session.find_duplicates()
        if duplicates:
            lines.append("")
            lines.append(f"Duplicates ({len(duplicates)}):")
            for orig, dup in duplicates:
                lines.append(f"  {orig.tool_name}({orig.args_hash})")
        
        lines.append("")
        lines.append("Call sequence:")
        for i, call in enumerate(self.session.calls):
            lines.append(f"  {i+1}. {call}")
        
        return "\n".join(lines)

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #14e08272
def run_scenario_validation(
    session_path: Path,
    scenario_name: str
) -> Dict[str, Any]:
    """Load a recorded session and validate against a scenario."""
    session = ToolCallSession.load(session_path)
    scenario = SCENARIOS.get(scenario_name)
    
    if not scenario:
        return {"error": f"Unknown scenario: {scenario_name}"}
    
    return scenario.validate(session)

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #c6bde021
def analyze_session_efficiency(session: ToolCallSession) -> Dict[str, Any]:
    """Analyze session for efficiency metrics."""
    duplicates = session.find_duplicates()
    total_time = sum(c.duration_ms for c in session.calls)
    
    return {
        "total_calls": len(session.calls),
        "unique_calls": len(session.calls) - len(duplicates),
        "duplicate_calls": len(duplicates),
        "duplicate_ratio": len(duplicates) / max(len(session.calls), 1),
        "total_time_ms": total_time,
        "avg_call_time_ms": total_time / max(len(session.calls), 1),
        "wasted_time_ms": sum(
            dup.duration_ms for _, dup in duplicates
        ),
        "efficiency_score": 1.0 - (len(duplicates) / max(len(session.calls), 1))
    }

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #97ba851e
from ..utils.logs import log

# Global recorder instance
_recorder: Optional[McpRecorder] = None
_recording_enabled: bool = False


def get_recorder() -> Optional[McpRecorder]:
    """Get the current recorder instance."""
    global _recorder
    return _recorder


def start_recording() -> McpRecorder:
    """Start recording tool calls."""
    global _recorder, _recording_enabled
    _recorder = McpRecorder()
    _recording_enabled = True
    log.info(f"Started recording session: {_recorder.session.session_id}")
    return _recorder


def stop_recording() -> Optional[ToolCallSession]:
    """Stop recording and return the session."""
    global _recorder, _recording_enabled
    _recording_enabled = False
    if _recorder:
        session = _recorder.session
        log.info(f"Stopped recording. Total calls: {len(session.calls)}")
        return session
    return None


def is_recording() -> bool:
    """Check if recording is enabled."""
    return _recording_enabled


def record_call(tool_name: str, args: Dict[str, Any], result: Any, duration_ms: float, success: bool, error: Optional[str] = None) -> None:
    """Record a tool call if recording is enabled."""
    global _recorder
    if _recording_enabled and _recorder:
        call = ToolCall(
            tool_name=tool_name,
            args=args,
            result=result if isinstance(result, dict) else {"value": str(result)},
            duration_ms=duration_ms,
            success=success,
            error=error
        )
        _recorder.session.add(call)

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #327e3472
def enable_auto_recording(mcp) -> None:
    """Patch MCP to automatically record all tool calls when recording is enabled.
    
    Call this after creating the MCP but before running it.
    """
    original_call_tool = mcp.call_tool
    
    async def recording_call_tool(name: str, arguments: dict) -> Any:
        start_time = time.time()
        error_msg = None
        success = True
        result = None
        
        try:
            result = await original_call_tool(name, arguments)
            # Check if result indicates failure
            if isinstance(result, dict) and result.get("ok") is False:
                success = False
                error_msg = result.get("error", "Unknown error")
        except Exception as e:
            success = False
            error_msg = str(e)
            raise
        finally:
            duration_ms = (time.time() - start_time) * 1000
            # Record the call
            record_call(
                tool_name=name,
                args=arguments,
                result=result,
                duration_ms=duration_ms,
                success=success,
                error=error_msg
            )
        
        return result
    
    mcp.call_tool = recording_call_tool
    log.info("Auto-recording enabled for MCP tool calls")

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #db289614
import tempfile
import shutil


def create_test_project(name: str = "test_project") -> Path:
    """Create a minimal nbdev test project for agent testing.
    
    Returns path to the temporary project directory.
    """
    import nbformat
    
    # Create temp directory
    base = Path(tempfile.mkdtemp(prefix=f"nbdev_test_{name}_"))
    nbs_dir = base / "nbs"
    lib_dir = base / name
    
    nbs_dir.mkdir()
    lib_dir.mkdir()
    
    # Create settings.ini
    settings = base / "settings.ini"
    settings.write_text(f"""[DEFAULT]
lib_name = {name}
nbs_path = nbs
lib_path = {name}
version = 0.0.1
""")
    
    # Create a notebook with some issues for testing
    nb = nbformat.v4.new_notebook()
    nb.cells = [
        nbformat.v4.new_code_cell("#| default_exp core"),
        nbformat.v4.new_code_cell('''#| export
def hello():
    """Say hello."""
    return "Hello, World!"
'''),
        nbformat.v4.new_code_cell('''#| export
from .utils import helper  # Relative import (lint issue)

def greet(name):
    return f"Hello, {name}!"
'''),
        nbformat.v4.new_code_cell('''# Test cell
assert hello() == "Hello, World!"
'''),
    ]
    
    nb_path = nbs_dir / "00_core.ipynb"
    with open(nb_path, 'w') as f:
        nbformat.write(nb, f)
    
    # Create a second notebook
    nb2 = nbformat.v4.new_notebook()
    nb2.cells = [
        nbformat.v4.new_code_cell("#| default_exp utils"),
        nbformat.v4.new_code_cell('''#| export
def helper():
    """A helper function."""
    return "helping"
'''),
    ]
    
    nb2_path = nbs_dir / "01_utils.ipynb"
    with open(nb2_path, 'w') as f:
        nbformat.write(nb2, f)
    
    # Create a .py file (generated)
    py_file = lib_dir / "core.py"
    py_file.write_text('''# AUTOGENERATED by nbdev
def hello():
    """Say hello."""
    return "Hello, World!"
''')
    
    (lib_dir / "__init__.py").write_text("")
    
    return base


def cleanup_test_project(path: Path) -> None:
    """Remove a test project directory."""
    if path.exists() and path.is_dir():
        shutil.rmtree(path)

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #c897f48b
TEST_PROMPTS = {
    "edit_py_file": """Edit the function `hello` in {lib_name}/core.py to add a docstring.""",
    
    "fix_lint": """Check this project for lint issues and fix any relative imports.""",
    
    "explore": """What functions does this project export? List them all.""",
    
    "run_tests": """Run the tests for this project and report the results.""",
    
    "add_function": """Add a new function called `goodbye` to the core module that returns "Goodbye!".""",
}


def get_test_prompt(scenario: str, project_path: Path) -> str:
    """Get a test prompt for a scenario with project path substituted."""
    template = TEST_PROMPTS.get(scenario, "")
    lib_name = "test_project"  # Default
    
    settings = project_path / "settings.ini"
    if settings.exists():
        import configparser
        cfg = configparser.ConfigParser()
        cfg.read(settings)
        lib_name = cfg.get("DEFAULT", "lib_name", fallback="test_project")
    
    return template.format(lib_name=lib_name, project_path=project_path)

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #15ff34bd
import subprocess
import os


def run_agent_test(
    agent: str,  # "claude" or "codex"
    scenario: str,
    project_path: Optional[Path] = None,
    timeout: int = 120,
    save_session: Optional[Path] = None
) -> Dict[str, Any]:
    """Run an automated agent test.
    
    Creates a test project, invokes the agent with a scenario prompt,
    records tool calls, and validates against expected behavior.
    
    Args:
        agent: Which agent CLI to use ("claude" or "codex")
        scenario: Test scenario name (edit_py_file, fix_lint, etc.)
        project_path: Optional existing project to test (creates temp if None)
        timeout: Max seconds to wait for agent
        save_session: Optional path to save session JSON
    
    Returns:
        Dict with test results including passed, failures, stats
    """
    # Create test project if not provided
    cleanup = False
    if project_path is None:
        project_path = create_test_project(f"agent_test_{scenario}")
        cleanup = True
    
    try:
        # Get the test prompt
        prompt = get_test_prompt(scenario, project_path)
        
        # Build agent command
        if agent == "claude":
            cmd = ["claude", "--print", "-p", prompt]
        elif agent == "codex":
            cmd = ["codex", "-q", prompt]
        else:
            return {"ok": False, "error": f"Unknown agent: {agent}"}
        
        # Set environment to enable auto-recording
        env = os.environ.copy()
        env["NBDEV_MCP_AUTO_RECORD"] = "1"
        env["NBDEV_MCP_PROJECT"] = str(project_path)
        
        # Create temp file for session output
        session_file = save_session or Path(tempfile.mktemp(suffix=".json"))
        env["NBDEV_MCP_SESSION_FILE"] = str(session_file)
        
        # Run agent
        log.info(f"Running {agent} with scenario '{scenario}'...")
        try:
            result = subprocess.run(
                cmd,
                cwd=str(project_path),
                env=env,
                capture_output=True,
                text=True,
                timeout=timeout
            )
        except subprocess.TimeoutExpired:
            return {
                "ok": False,
                "error": f"Agent timed out after {timeout}s",
                "scenario": scenario
            }
        
        # Load and validate session
        if session_file.exists():
            session = ToolCallSession.load(session_file)
            validation = SCENARIOS[scenario].validate(session)
            efficiency = analyze_session_efficiency(session)
            
            return {
                "ok": validation["passed"],
                "scenario": scenario,
                "agent": agent,
                "validation": validation,
                "efficiency": efficiency,
                "agent_output": result.stdout[:1000] if result.stdout else None,
                "agent_stderr": result.stderr[:500] if result.stderr else None,
                "session_file": str(session_file) if save_session else None
            }
        else:
            return {
                "ok": False,
                "error": "No session file created - MCP may not have been used",
                "scenario": scenario,
                "agent_output": result.stdout[:1000] if result.stdout else None,
                "agent_stderr": result.stderr[:500] if result.stderr else None
            }
    
    finally:
        if cleanup:
            cleanup_test_project(project_path)


def run_all_agent_tests(
    agent: str = "claude",
    scenarios: Optional[List[str]] = None,
    save_dir: Optional[Path] = None
) -> Dict[str, Any]:
    """Run all agent tests and return summary.
    
    Args:
        agent: Which agent CLI to use
        scenarios: List of scenarios to test (all if None)
        save_dir: Directory to save session files
    
    Returns:
        Summary with passed/failed counts and details
    """
    scenarios = scenarios or list(SCENARIOS.keys())
    results = []
    
    if save_dir:
        save_dir = Path(save_dir)
        save_dir.mkdir(parents=True, exist_ok=True)
    
    for scenario in scenarios:
        save_path = save_dir / f"{scenario}.json" if save_dir else None
        result = run_agent_test(agent, scenario, save_session=save_path)
        results.append(result)
        
        status = "PASS" if result.get("ok") else "FAIL"
        log.info(f"  {status}: {scenario}")
    
    passed = sum(1 for r in results if r.get("ok"))
    failed = len(results) - passed
    
    return {
        "total": len(results),
        "passed": passed,
        "failed": failed,
        "pass_rate": passed / len(results) if results else 0,
        "results": results
    }

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #8c4c3139
def add_recording_tools(mcp) -> None:
    """Add recording control tools to MCP server."""
    
    @mcp.tool()
    def start_session_recording(ctx: Context) -> Dict[str, Any]:
        """Start recording MCP tool calls for analysis.
        
        Returns session ID that can be used to retrieve the recording.
        """
        recorder = start_recording()
        return {
            "ok": True,
            "session_id": recorder.session.session_id,
            "message": "Recording started"
        }
    
    @mcp.tool()
    def stop_session_recording(
        ctx: Context,
        save_path: Optional[str] = None
    ) -> Dict[str, Any]:
        """Stop recording and optionally save to file.
        
        Args:
            save_path: Optional path to save the session JSON.
        
        Returns session statistics and optionally the file path.
        """
        session = stop_recording()
        if not session:
            return {"ok": False, "error": "No active recording"}
        
        result = {
            "ok": True,
            "session_id": session.session_id,
            "stats": session.to_dict()["stats"]
        }
        
        if save_path:
            path = Path(save_path)
            session.save(path)
            result["saved_to"] = str(path)
        
        return result
    
    @mcp.tool()
    def get_recording_status(ctx: Context) -> Dict[str, Any]:
        """Check if recording is active and get current stats."""
        recorder = get_recorder()
        if not is_recording() or not recorder:
            return {"ok": True, "recording": False}
        
        return {
            "ok": True,
            "recording": True,
            "session_id": recorder.session.session_id,
            "calls_so_far": len(recorder.session.calls),
            "duplicates_so_far": len(recorder.session.find_duplicates())
        }
    
    @mcp.tool()
    def validate_session(
        ctx: Context,
        session_path: str,
        scenario: str
    ) -> Dict[str, Any]:
        """Validate a recorded session against a test scenario.
        
        Args:
            session_path: Path to session JSON file.
            scenario: Name of scenario (edit_py_file, fix_lint, explore, find_duplicates, run_tests).
        """
        return run_scenario_validation(Path(session_path), scenario)

# %% ../../nbs/99_tests/01_agent_e2e.ipynb #96c27515
#| export

